name: Python CI

on:
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout my project
      - name: Install Python 3v10
        uses : actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run : |
         python -m pip install -r requirements.txt
         pip install pylint
      - name : pylint
        run : |
         pylint
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "credentials.json"
          json: ${{ secrets.MY_JSON }}


       